version: '3.7'

services:
  # mongodb:
  #   container_name: dmind_mongo
  #   image: mongo
  #   restart: always
  #   env_file: ./.env
  #   # environment:
  #   #   - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
  #   #   - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./db:/data/db
  go_server:
    container_name: go_server
    build:
      context: ./go-server/
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    expose:
      - '3001'
    ports:
      - '3001:3001'
    command: /server
  go_server2:
    container_name: go_server2
    build:
      context: ./go-server2/
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    expose:
      - '3002'
    ports:
      - '3002:3002'
    command: /server
  nginx:
    build: ./nginx
    ports:
    - '3000:3000'
    depends_on:
    - go_server
    - go_server2


    # external_links:
    #   - mongodb
    # depends_on:
    #   - mongodb



#   mongodb:
#     image: mongo
#     restart: unless-stopped
#     env_file: ./.env
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
#       - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
#     ports:
#       - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
#     volumes:
#       - db:/data/db
#   app:
#     depends_on:
#       - mongodb
#     build: ./chatbot
#     restart: unless-stopped
#     env_file: ./.env
#     ports:
#       - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
#     environment:
#       - DB_HOST=mongodb
#       - DB_USER=$MONGODB_USER
#       - DB_PASSWORD=$MONGODB_PASSWORD
#       - DB_NAME=$MONGODB_DATABASE
#       - DB_PORT=$MONGODB_DOCKER_PORT
#     stdin_open: true
#     tty: true

# volumes:
#   db: